# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Author.create(id:1, name:'Amy Cuddy', dob:'7/27/72', nationality:'United States', awards:'"Rising Star Award, Association for Psychological Science (APS), 2011, Psychology Today, The Top 10 Psychology Studies of 2010 (Carney, Cuddy, & Yap, 2010)', biography:'Amy Joy Casselberry Cuddy is an American social psychologist known for her research on stereotyping and discrimination, emotions, power, nonverbal behavior, and the effects of social stimuli on hormone levels. She is an Associate Professor of Business Administration at Harvard Business School, in the Negotiation, Organizations & Markets Unit.', image_url:'http://www.socialpsychology.org/thumb/3982/0/md.jpg')
Author.create(id:2, name:'Ravi Rossi', dob:'6/18/71', nationality:'United States', awards:'Danny Meyer Empire Builder of the Year 2015, International Tastemaker of the Year',
  biography:'Ravi DeRossi began his career as an artist but soon set his sights on New York nightlife. His first venture, the Bourgeois Pig, was a press favorite. Then he co-founded Death & Co. and shortly thereafter Desnuda Cevicheria, described by the New York Times as one of the most creative and innovative restaurants that New York has to offer. Mayahuel, his tequila and mescal bar, won the Best New Cocktail Bar Award at Tales of the Cocktail, and then he opened the Cuban rum bar Cienfuegos, among other notable establishments.', image_url:'http://foodbookfair.com/wp-content/uploads/2015/02/IMG_0208-200x200.jpg')
Author.create(id:3, name:'George R. R. Martin', dob:'9/20/48', nationality:'United States',
  awards:'Hugo Award for Best Novella for "A Song for Lya, Locus Award for Best Fantasy Novel for "A Dance with Dragons"', biography:'George Raymond Richard Martin, often referred to as GRRM, is an American novelist and short story writer in the fantasy, horror, and science fiction genres, a screenwriter, and television producer.', image_url:'ttp://www-images.theonering.org/torwp/wp-content/uploads/2015/08/George-RR-Martin-thumb.jpg')
Author.create(id:4, name:'S. M. Stirling', dob:'9/30/53', nationality:'Canada', awards:'idewise Award for Best Long-Form Alternate History, Prometheus Award for Best Novel', biography:'Stephen Michael Stirling is a French-born Canadian-American science fiction and fantasy author. Stirling is probably best known for his Draka series of alternate history novels and his later time travel/alternate history Nantucket series and Emberverse series.', image_url:'http://d.gr-assets.com/authors/1440541452p5/14002.jpg')
Author.create(id:5, name:'Frank Herbert', dob:'10/8/20', nationality:'United States', awards:'Science Fiction Hall of Fame, Nebula Award for Best Novel', biography:'Frank Patrick Herbert, Jr. was an American science fiction writer best known for the novel ""Dune"" and its five sequels. Though he became famous for science fiction, he was also a newspaper journalist, photographer, short story writer, book reviewer, ecological consultant and lecturer.', image_url:'http://d.gr-assets.com/authors/1168661521p5/58.jpg')
Author.create(id:6, name:'Robert Jordan', dob:'10/17/48', nationality:'United States', awards:'Goodreads Choice Awards Best Fantasy', biography:'James Oliver Rigney, Jr., better known by his pen name Robert Jordan, was an American author of epic fantasy. He is best known for The Wheel of Time series, which comprises 14 books and a prequel novel.', image_url:'http://d.gr-assets.com/authors/1175475715p5/6252.jpg')

